services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.13.0
    restart: unless-stopped
    ports:
      - "5000:5000"
    command:
      - mlflow
      - server
      - --host
      - 0.0.0.0
      - --port
      - "5000"
      - --backend-store-uri
      - sqlite:////mlflow/mlflow.db
      - --default-artifact-root
      - /mlflow/artifacts
      - --allowed-hosts
      - "*"
    volumes:
      - mlflow_data:/mlflow

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.158.0
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./config/otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "4318:4318"

  prometheus:
    image: prom/prometheus:v3.13.2
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - mlflow_prometheus_data:/prometheus
      - ./config/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9099:9090"         

volumes:
  mlflow_data:
  mlflow_prometheus_data:
