name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: "25"
          distribution: "temurin"
          cache: maven
      - name: Build pdf-qa
        run: mvn -B -q package
        working-directory: ./pdf-qa
      - name: Build simple-text-to-sql
        run: mvn -B -q package
        working-directory: ./simple-text-to-sql 
      - name: Build web-page-qa
        run: mvn -B -q package
        working-directory: ./web-page-qa   
